grammar_task:
  description: >
    Edit the text file content below to correct grammar and punctuation issues:

    {notes}

    Ensure all changes preserve the original meaning and maintain academic tone.
    Your final result MUST be a fully edited version of the file with corrections applied.
    Save your output as an edited version to be passed to the final editor.
  # Input: {notes}
  expected_output: >
    The cleaned-up version of the text with improved grammar and clarity.
  agent: grammar_expert
  output_key: grammar_output

fact_check_task:
  description: >
    Review the following notes for factual inaccuracies:

    {notes}

    For each inaccuracy, apply a correction and cite credible sources if possible.
    Your final result MUST be a corrected version of the content.
    Save your output to be passed to the final editor.

  expected_output: >
    A fact-checked report listing inaccuracies found, corrections, and supporting references.
  agent: factual_expert
  input_keys: grammar_output
  output_key: fact_output

outline_task:
  description: >
    Convert the following notes into the Outline Method format:

    {notes}

    Use indentation and bullets to clearly structure topics and subpoints. Format your response
    in clean Markdown.
  expected_output: >
    A Markdown document formatted in the Outline Method.
  agent: outline_expert
  input_keys: fact_output
  # output_key: formatted_notes

cornell_task:
  description: >
    Convert the following notes into the Cornell Method format:

    {notes}

    Format the result with three clearly defined sections:
    - Cue column with keywords or questions: 
    - Notes section with expanded information: Main ideas, details, and examples 
    - Summary at the bottom

    Output must be in Markdown format.
    Ensure the layout is:
      # Cornell Notes
      ## Cues
      ## Notes
      ## Summary
    
  expected_output: >
    Markdown document using the Cornell Method format.
  agent: cornell_expert
  input_keys: fact_output

boxing_task:
  description: >
    Convert the following notes into the Boxing Method format:

    {notes}

    Use boxes to separate different sections and include a summary at the end.
    Format your response in clean Markdown.
  expected_output: >
    A Markdown document formatted in the Boxing Method.
  agent: boxing_expert
  input_keys: fact_output

flashcard_task:
  description: >
    Create flashcards from the following notes:

    {notes}

    Rules:
    - Each flashcard must have a clear question and concise answer.
    - Focus on key facts, definitions, dates, and concepts.
    - Format as a Markdown list:

      - **Q: What is X?**  
        **A:** Explanation...

    - Generate 5–15 cards depending on the content.

    Your final answer MUST be a set of markdown-formatted Q&A flashcards.
    Save your output to `flashcards.md`.
  agent: flashcard_expert
  input_keys: fact_output
  expected_output: >
   A set of markdown flashcards saved to flashcards.md
